---
title: "k segment HMM"
author: "Jitao Wang"
date: "6/27/2019"
output: html_document
---

```{r}
library(ggplot2)
library(reshape2)
library(matrixStats)
```

Reference
1. Statistical Inference in Hidden Markov Models Using k-Segment Constraints

```{r}
## simulate one observed sequence y with hidden state x 
set.seed(100)
transMtx = matrix(c(0.98,0.015,0.005,
                     0.05,0.98,0.015,
                     0.015,0.005,0.98),byrow = TRUE,ncol = 3)   ## transition matrix; 3 hidden states
pi = c(0,0.95,0.05)  ## intial probability
mu = c(-2,-1,1)      ## mean values for 3 hidden states
sigma = rep(0.9,3)   ## variance

T = 100              ## length of sequence
M = dim(transMtx)[1] ## number of hidden states

x = rep(NA,T)
x[1] = sample(1:M,1,prob = pi)                   ## first hidden state
for (i in 2:T){
  x[i] = sample(1:M,1,prob = transMtx[x[i-1],])  ## remaining hidden states
}

y = rep(NA,T); y_real = rep(NA,T)
for (i in 1:T){
  idx = x[i]
  y_real[i] = mu[idx]
  y[i] = rnorm(1,y_real[i],sigma[idx])           ## add gaussian noise
}

## plot the sequence 
dat = data.frame(id = 1:T, x = x, y = y, y_real = y_real)
p <- ggplot(dat,aes(x = id, y = y_real))+
  geom_line()+
  geom_point(aes(x = id, y = y),size = 0.5)+
  xlim(0,T)+
  ylim(-6,4)
p

NumberofSegments = length(rle(x)$value) ## number of segments 
NumberofSegments
```

#optimal coding#
```{r}
# Traditional Viterbi algorithm and Backward algorithm
## T: length of obs; N: num of obs; M: num of hidden states
## obs: T * 1
## transMtx: M * M
## emisMtx: M * N
## pi: start prob, M * 1
my_viterbi_gaussian <- function(obs,mu,sigma,transMtx,pi){
  T = length(obs)
  M = length(pi)
  N = length(mu)
  
  D = array(NA,dim=c(M,T))
  G = array(NA,dim=c(M,T))
  
  G[,1] =  log(dnorm(obs[1],mu,sigma)) + log(pi)
  

  for (j in 2:T){
    py_x = dnorm(obs[j],mu,sigma)
    for (i in 1:M){
      tmp = G[,j-1] + log(transMtx[,i]) + log(py_x[i])
      G[i,j] = max(tmp)
      D[i,j] = which.max(tmp)
    }
  }
  
  return(list("D" = D,"G" = G[,T]))
}

my_backtrace <- function(D,G_T,k){
  M = length(G_T)
  T = dim(D)[2]
  x = rep(NA,T)

  
  x[T] = which.max(G_T)

  for (t in (T-1):1){
    x[t] = D[x[t+1],t+1]
  }
  return(x)
}
```

```{r}
# Viterbi algorithm with k-segment constraint
## T: length of sequence; N: num of class of observed; M: num of hidden states
## obs: T * 1
## transMtx: M * M
## emisMtx: M * N
## pi: intial prob, M * 1
my_viterbi_constraint <- function(obs,mu,sigma,transMtx,pi){
  T = length(obs)
  M = length(pi)
  
  D = array(NA,dim=c(M,T,T))                         ## D matrix; record the path; used in backtrace;
  ## meaning of indexes: state, number of segments, location of observation
 
  G_current = matrix(NA,ncol = T, nrow = M)          ## G matrix
  ## G[a,b] means log probability of the most probable state sequence with b number of segments and the last state is a 
  transMtx_NoDiag = transMtx - diag(diag(transMtx))
  
  G1 =  dnorm(obs[1],mu,sigma,log = TRUE) + log(pi)  ## log probability of first observation
  
  lpy_x = dnorm(obs[2],mu,sigma,log=TRUE)

  G_current[,1] = G1 + log(diag(transMtx)) + lpy_x   ## log prob of no transition
  for (i in 1:M){
    tmp = G1 + log(transMtx_NoDiag[,i]) + lpy_x[i]   ## log prob with transition
    G_current[i,2] = max(tmp)                        ## find the most probable path
    D[i, 1, 2] = i                                   ## store the origin of the path
    D[i, 2, 2] = which.max(tmp)
  }
  
  for (s in 3:T){                                    ## s: location of the observation
    lpy_x = dnorm(obs[s],mu,sigma,log = TRUE)

    G_pre = G_current
    # update G matrix
    # k: number of segment
    
    ## k = 1
    G_current[,1] = G_pre[,1] + log(diag(transMtx)) + lpy_x
    D[,1,s] = 1:M

    ## k = 2 to s-1
    for (k in 2:(s-1)){
      for (i in 1:M){
        ## calculate the log probabilities from 3 previous possible states
        tmp = G_pre[,c(k-1,k)] + cbind(log(transMtx_NoDiag[,i]),log(diag(diag(transMtx))[,i])) + lpy_x[i]
        G_current[i,k] = max(tmp)
        D[i,k,s] = which.max(tmp)
      }
    }
    ## k = s
    for (i in 1:M){
      tmp = G_pre[,s-1] + log(transMtx_NoDiag[,i]) + lpy_x[i]
      G_current[i,s] = max(tmp)
      D[i,s,s] = which.max(tmp)
    }
  }
  
  return(list("D" = D,"G" = G_current))
  }

## Backtrace the most probable path
## D: D matrix from my_viterbi_constraint()
## G: G matrix from my_viterbi_constraint()
## k: number of segments
my_backtrace_constraint <- function(D,G,k){
  M = dim(G)[1]
  T = dim(D)[3]
  x = rep(NA,T)

  ## the most probale state of the last postion
  x[T] = ifelse(which.max(G[,k])<=M,which.max(G[,k]),which.max(G[,k])-M)
  ## backtrace using D matrix
  for (t in (T-1):1){
    x[t] = ifelse(D[x[t+1],k,t+1] <= M, D[x[t+1],k,t+1], D[x[t+1],k,t+1]-M)
    k = k - (x[t] != x[t+1])
  }
  return(x)
}
```



```{r}
## test result with k-segment constraint
result_cons = my_viterbi_constraint(y,mu,sigma,transMtx,pi)
path_cons = my_backtrace_constraint(result_cons$D,result_cons$G,NumberofSegments)
## test result with normal hmm algorithm
result = my_viterbi_gaussian(y,mu,sigma,transMtx,pi)
path = my_backtrace(result$D,result$G)

# plot the result
# plot 1
par(mfrow = c(3,1))
plot(x,type="l"); plot(path_cons,type = "l");plot(path,type = "l")

# plot 2 
datcomp = data.frame(id = 1:T,x_real = x,x_viterbi_k = path_cons)
datm = melt(datcomp,id.vars = 1)
p1 <- ggplot(datm,aes(x = id, y = value))+
  geom_line(aes( color = variable,group = variable))+
  scale_color_manual(values = c("red","blue"),labels = c("x_real","x_viterbi_k")) + 
  ggtitle("hmm with k constriant")

datcomp = data.frame(id = 1:T,x_real = x,x_viterbi = path)
datm = melt(datcomp,id.vars = 1)
p2 <- ggplot(datm,aes(x = id, y = value))+
  geom_line(aes( color = variable,group = variable))+
  scale_color_manual(values = c("red","green"),labels = c("x_real","x_viterbi")) +
   ggtitle("normal hmm")
p1;p2;
```

#probability computation
```{r}
## forward algorithm; aka alpha message
## T: length of sequence; N: num of class of observed; M: num of hidden states
## obs: T * 1
## transMtx: M * M
## emisMtx: M * N
## pi: intial prob, M * 1
## return log alpha message
lmy_forward_constraint <- function(obs,mu,sigma,transMtx,pi,kmax){
  T = length(obs)
  M = length(pi)
  
  ## lA[a,b,c]: alpha message with b segments at location c as state a
  lA = array(NA,dim=c(M,kmax,T))
  transMtx_NoDiag = transMtx - diag(diag(transMtx))
  lpy_x = mapply(obs,FUN = function(x) dnorm(x,mu,sigma,log = TRUE))
  
  # upadte lA 
  ## first observation
  lA[,1,1] =  lpy_x[,1] + log(pi)
  
  ## observation 2:T
  for (s in 2:T){
    ## k = 1
    lA[,1,s] = lA[,1,s-1] + log(diag(transMtx)) + lpy_x[,s]
  }
  if (kmax == 1){ return(lA) }
    ## k=2 to k=kmax
  for (k in 2:kmax){
    ## k = k at position k
    for (i in 1:M) { lA[i,k,k] = logSumExp(lA[,k-1,k-1] + log(transMtx_NoDiag[,i])) + lpy_x[i,k] } 
    
    if( k < T ){
      for (s in (k+1):T){
        for (i in 1:M){
          tmp = lA[,c(k-1,k),(s-1)] + log(cbind(transMtx_NoDiag[,i],diag(diag(transMtx))[,i]))
          lA[i,k,s] = logSumExp(tmp) + lpy_x[i,s]
        }
      }
    }
  }
  
  return(lA)
}
```

```{r}
## backward algorithm; aka beta message
## T: length of obs; N: num of obs; M: num of hidden states
## obs: T * 1
## transMtx: M * M
## emisMtx: M * N
## pi: start prob, M * 1
## return: log beta message
lmy_backward_constraint <- function(obs,mu,sigma,transMtx,pi,kmax){
  T = length(obs)
  M = length(pi)
  
  lB = array(NA,dim=c(M,kmax,T))
  transMtx_NoDiag = transMtx - diag(diag(transMtx))
  lpy_x = mapply(obs,FUN = function(x) dnorm(x,mu,sigma,log = TRUE))
  
  # initilization
  lB[,,T] = 0
  
  for (s in (T-1):kmax){
    lB[,kmax,s] = lB[,kmax,s+1] + log(diag(transMtx)) + lpy_x[,s+1]
  }
  if (kmax == 1){ return(lB) }
  
  for (k in (kmax-1):1){
    for (s in (T-1):k){
      for (i in 1:M){
        tmp = lB[,c(k,k+1),s+1] + log(cbind(diag(diag(transMtx))[,i],transMtx_NoDiag[i,])) + cbind(lpy_x[,s+1],lpy_x[,s+1])
        lB[i,k,s] = logSumExp(tmp)
      }
    }
  }

  return(lB)
}
```

```{r}
lA = lmy_forward_constraint(y,mu,sigma,transMtx,pi,5)
lB = lmy_backward_constraint(y,mu,sigma,transMtx,pi,5)
lprob = lA +lB

# functions below are defined at the end of this document; used for benchmark
#A = my_forward_constraint(y,mu,sigma,transMtx,pi)
#B = my_backward_constraint(y,mu,sigma,transMtx,pi)
#prob = A * B

#sum(prob[,,T]);sum(prob[,,1],na.rm = TRUE)
```

#LEARNING WITH k-SEGMENT CONSTRAINTS#
```{r}
transMtx = matrix(c(0.98,0.015,0.005,
                     0.05,0.98,0.015,
                     0.015,0.005,0.98),byrow = TRUE,ncol = 3)
pi = c(0,0.95,0.05)
mu = c(-2,-1,1)
sigma = rep(0.2,3)

D = 10       ## number of sequences to be generated
T = 100
KMAX = 1

N = length(mu)
M = dim(transMtx)[1]

seqs = c()
for (i in 1:D){
  x = rep(NA,T)
  x[1] = sample(1:M,1,prob = pi)
  for (i in 2:T){
    x[i] = sample(1:M,1,prob = transMtx[x[i-1],])
  }
  KMAX = ifelse(length(rle(x)$value)>KMAX,length(rle(x)$value),KMAX)
  y = rep(NA,T); y_real = rep(NA,T)
  for (i in 1:T){
    idx = x[i]
    y_real[i] = mu[idx]
    y[i] = rnorm(1,y_real[i],sigma[idx])
  }
  seqs = rbind(seqs,y)
}
## maximum number of segments among all sequences
KMAX
```

```{r}
# part of EM algorithm; used to calculate log Pr(x_n|s_N <= k, y) and log Pr(x_{n-1},x_n | s_N <= k,y)
# for single sequence
## seq: observed sequence
## M: number of hidden states
## mu: mean of hidden states
## sigma: sigma of hidden states
## pi: intial probabilities
## kmax: maximum number of segments
my_em_constraint_single = function(seq, M,mu,sigma,pi,transMtx,kmax){
  T = length(seq)
  ## calcualte p(x)
  lPX = array(NA,dim=c(M,T))    ## log Pr(x_n|s_N <= k, y)
  lA = lmy_forward_constraint(obs=seq,mu = mu,sigma = sigma, transMtx = transMtx, pi = pi,kmax = kmax)
  lB = lmy_backward_constraint(obs=seq,mu = mu,sigma = sigma, transMtx = transMtx, pi = pi,kmax = kmax)
  lprob = lA + lB
  llk = logSumExp(lprob[,,T])
  
  for (k in 1:T){
    for (i in 1:M){
      lPX[i,k] = logSumExp(lprob[i,,k]-llk,na.rm = TRUE)
    }
  }
  
  ## calculate pxx
  transMtx_NoDiag = transMtx - diag(diag(transMtx))
  lPXX = array(NA,dim = c(M,M,T))  ## log Pr(x_{n-1},x_n | s_N <= k,y)
  for (k in 2:T){
    lpy_x = dnorm(seq[k],mu,sigma,log = TRUE)
    
    ## xn = xn-1 and sn = sn-1
    tmp = apply(lA[,,k-1],2,function(x) x + lpy_x + log(diag(transMtx))) + lB[,,k]
    for (i in 1:M){
      lPXX[i,i,k] = logSumExp(tmp[i,]-llk,na.rm = TRUE)
    }
    
    ## xn != xn-1 and sn = sn-1 + 1
    for (j in 1:M){
      for (i in 1:M){
        if( i != j){
          tmp = lA[i,-kmax,k-1] + log(transMtx_NoDiag[i,j]) + lpy_x[j] + lB[j,-1,k]
          lPXX[i,j,k] = logSumExp(tmp-llk,na.rm = TRUE)
        }
      }
    }
  }
  return(list("lPX" = lPX,"lPXX" = lPXX,"LLK"=llk))
}
```

```{r}
# EM algorithm with k constraint
my_em_constraint= function(seqs, M,mu_init = runif(N,min = min(seqs),max = max(seqs)),sigma_init = rep(runif(1,0,1),M),kmax = 10){
  T = dim(seqs)[2] ; D = dim(seqs)[1]
  pi = runif(3); pi = pi/sum(pi);
  transMtx = matrix(runif(M*M),ncol = M); transMtx = t(apply(transMtx,1,function(x) x/sum(x)))
  mu = mu_init
  sigma = sigma_init

  ## intialization
  iter = 0
  epsilon = 1e-8       ## threshold
  llk_pre = -100000000; llk_current = -1000000
  
  ## run EM
  while(llk_current - llk_pre > epsilon){
    llk_pre = llk_current
    sum_pi = rep(0,M); sum_xx2 = matrix(0,nrow = M,ncol = M); sum_x2 = rep(0,M); sum_xy1 = matrix(0,nrow = M, ncol=N); sum_x1 = rep(0,M);
    sum_xy_mean = rep(0,N); sum_xy_sq = rep(0,N)
    llk_current = 0;
    
    for (num in 1:D){
      seq = seqs[num,]
      output = my_em_constraint_single(seq = seq,M = M,mu = mu,sigma = sigma,pi = pi,transMtx = transMtx,kmax = kmax)
      
      llk_current = llk_current + output$LLK
      #print(output$LLK)
      
      sum_pi = sum_pi + exp(output$lPX[,1]); 
      sum_xx2 = sum_xx2 + rowSums(exp(output$lPXX),dims = 2,na.rm = TRUE);
      sum_x2 = sum_x2 + exp(apply(output$lPX[,-T],1,logSumExp));
      sum_x1 = sum_x1 + exp(apply(output$lPX,1,logSumExp));
      sum_xy_mean = sum_xy_mean + exp(output$lPX) %*% matrix(seq,ncol = 1)
      sum_xy_sq = sum_xy_sq + apply(exp(output$lPX) * (matrix(seq,ncol = T,nrow = M,byrow = TRUE) - matrix(mu,ncol = T,nrow = M))^2,1,sum)
    }
    
    pi = sum_pi/D                     ## update pi
    transMtx = sum_xx2/sum_x2         ## update transMtx
    mu = sum_xy_mean / sum_x1         ## update mu
    sigma = sqrt(sum_xy_sq / sum_x1)  ## update sigma
    iter = iter + 1
    print(paste(c("Iteration",iter,"end")))
  }
  
  return(list("pi"=pi,"transMtx"=transMtx,"mu" = mu,"sigma" = sigma,"llk"=llk_current,"iter"=iter))
}
```

```{r}
resultem = my_em_constraint(seqs,3,kmax = KMAX)
resultem
```

#PATH SAMPLING#
```{r}
## simulate one observed sequence y with hidden state x 
set.seed(100)
transMtx = matrix(c(0.98,0.015,0.005,
                     0.05,0.98,0.015,
                     0.015,0.005,0.98),byrow = TRUE,ncol = 3)   ## transition matrix; 3 hidden states
pi = c(0,0.95,0.05)  ## intial probability
mu = c(-2,-1,1)      ## mean values for 3 hidden states
sigma = rep(0.9,3)   ## variance

T = 100              ## length of sequence
M = dim(transMtx)[1] ## number of hidden states

x = rep(NA,T)
x[1] = sample(1:M,1,prob = pi)                   ## first hidden state
for (i in 2:T){
  x[i] = sample(1:M,1,prob = transMtx[x[i-1],])  ## remaining hidden states
}

y = rep(NA,T); y_real = rep(NA,T)
for (i in 1:T){
  idx = x[i]
  y_real[i] = mu[idx]
  y[i] = rnorm(1,y_real[i],sigma[idx])           ## add gaussian noise
}

## plot the sequence 
dat = data.frame(id = 1:T, x = x, y = y, y_real = y_real)
p <- ggplot(dat,aes(x = id, y = y_real))+
  geom_line()+
  geom_point(aes(x = id, y = y),size = 0.5)+
  xlim(0,T)+
  ylim(-6,4)
p

NumberofSegments = length(rle(x)$value) ## number of segments 
NumberofSegments
```

```{r}
# Forward filtering backward sampling algorithm for k constraint hmm
my_path_sampling = function(obs,mu,sigma,transMtx,pi,SamplesNum,kseg){
  T = length(obs)
  M = length(pi)
  N = length(mu)
  samples_x = array(NA,dim=c(SamplesNum,T))
  success = 0
  
  transMtx_NoDiag = transMtx - diag(diag(transMtx))
  lA = lmy_forward_constraint(obs,mu,sigma,transMtx,pi,kseg)
  
  while(success<SamplesNum){
    x = rep(NA,T); s = kseg;
    x[T] = sample(1:M,1,prob = exp(lA[,kseg,T]))
    for (j in (T-1):1){
      if(j>=s){
        if(s == 1){
          x[j] = x[j+1]
        }else{
          prob = exp(lA[,c(s-1,s),j]) * cbind(transMtx_NoDiag[,x[j+1]],diag(diag(transMtx))[,x[j+1]])
          tmp = sample(1:length(prob),1,prob = c(prob))
          x[j] = ifelse(tmp <= M,tmp,tmp-M)
          s = s - (x[j] != x[j+1])
        }
      }
    }
    if(!is.na(x[1])){
      success = success+1
      samples_x[success,] = x
    }
  }
  
  return(samples_x)
}
```


```{r}
## path sampling using FFBS
samples = my_path_sampling(y,mu,sigma,transMtx,pi,10,NumberofSegments)

# plot 1
par(mfrow = c(3,1))
for (i in 1:dim(samples)[1]){
  plot(samples[i,],type="l")
}

#plot 2
datcomp = data.frame(id = 1:T,x = t(samples))
library(reshape2)
datm = melt(datcomp,id.vars = 1)
p <- ggplot(datm,aes(x = id, y = value))+
  geom_line()
p
```



#Some functions may be useful#

```{r}
my_forward_constraint <- function(obs,mu,sigma,transMtx,pi){
  T = length(obs)
  M = length(pi)
  
  A = array(NA,dim=c(M,T,T))
  transMtx_NoDiag = transMtx - diag(diag(transMtx))
  
  A[,1,1] =  dnorm(obs[1],mu,sigma) * pi
  #A[,,1] = A[,,1] / sum(A[,,1],na.rm = TRUE)
  
  py_x = dnorm(obs[2],mu,sigma)
  A[,1,2] = A[,1,1] * diag(transMtx) * py_x
  for (i in 1:M){
    tmp = A[,1,1] * transMtx_NoDiag[,i]
    A[i,2,2] = sum(tmp) * py_x[i]
  }
  #A[,,2] = A[,,2] / sum(A[,,2],na.rm = TRUE)
  
  for (s in 3:T){
    py_x = dnorm(obs[s],mu,sigma)

    ## k = 1
    A[,1,s] = A[,1,s-1] * diag(transMtx) * py_x


    ## k = 2 to s-1
    for (k in 2:(s-1)){
      for (i in 1:M){
        tmp = A[,c(k-1,k),s-1] * cbind(transMtx_NoDiag[,i],diag(diag(transMtx))[,i])
        A[i,k,s] = sum(tmp) * py_x[i] 
      }
    }
    ## k = s
    for (i in 1:M){
      tmp = A[,s-1,s-1] * transMtx_NoDiag[,i]
      A[i,s,s] = sum(tmp) * py_x[i]
    }
    #A[,,s] = A[,,s] / sum(A[,,s],na.rm = TRUE)
  }
  
  
  return(A)
}
```

```{r}
my_backward_constraint <- function(obs,mu,sigma,transMtx,pi){
  T = length(obs)
  M = length(pi)
  
  B = array(NA,dim=c(M,T,T))
  transMtx_NoDiag = transMtx - diag(diag(transMtx))
  
  B[,,T] = B[,,T] ^ 0
  
  for (s in (T-1):1){
    
    py_x_p1 = dnorm(obs[s+1],mu,sigma)
    
    for (k in s:1){
      for (i in 1:M){
        tmp = B[,c(k,k+1),s+1] * cbind(diag(diag(transMtx))[,i],transMtx_NoDiag[i,]) * cbind(py_x_p1,py_x_p1)
        B[i,k,s] = sum(tmp)
      }
    }
  }
  
  return(B)
}
```


